server:
  port: 8080

spring:
  datasource:
    url:      ${DB_URL:jdbc:postgresql://localhost:5432/driveit}
    username: ${DB_USER:driveit}
    password: ${DB_PASSWORD:driveit}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true